export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const VIEW_CONTACT = "VIEW_CONTACT";
export const ADD_CONTACT = "ADD_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const RESET_CONTACT = "RESET_CONTACT";
export const SET_LOADER = "SET_LOADER";
